const { withPodfile } = require("expo/config-plugins");

/**
 * Fixes the MMKVCore build failure on the iOS 26 SDK.
 *
 * MMKVCore's AESCrypt.cpp wipes key material through `memset_s`, guarded by
 * `#elif defined(__STDC_LIB_EXT1__) || defined(MMKV_APPLE)` — so Apple builds
 * always take that branch. But the SDK only declares `memset_s` when
 * `__STDC_WANT_LIB_EXT1__ >= 1` is set at the moment <string.h> is first
 * processed, and CocoaPods force-includes MMKVCore-prefix.pch ahead of every
 * source file. By the time AESCrypt.cpp's own `#define` on line 21 is reached,
 * string.h's include guard has already closed, so the define does nothing and
 * the build dies with "use of undeclared identifier 'memset_s'".
 *
 * Setting it as a compiler-level define gets there before any header is read.
 *
 * This lives in a plugin rather than in ios/Podfile because /ios is gitignored
 * and regenerated by `expo prebuild` — including on EAS Build, which would
 * otherwise discard the fix and fail the same way.
 */
module.exports = function withMmkvMemsetFix(config) {
  return withPodfile(config, (config) => {
    const podfile = config.modResults.contents;

    if (podfile.includes("__STDC_WANT_LIB_EXT1__")) {
      return config;
    }

    const patch = `
    # See plugins/withMmkvMemsetFix.js — MMKVCore needs __STDC_WANT_LIB_EXT1__
    # defined at the compiler level for memset_s to be declared on the iOS SDK.
    installer.pods_project.targets.each do |target|
      next unless target.name == 'MMKVCore'
      target.build_configurations.each do |build_configuration|
        definitions = build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        definitions = [definitions] if definitions.is_a?(String)
        unless definitions.include?('__STDC_WANT_LIB_EXT1__=1')
          definitions << '__STDC_WANT_LIB_EXT1__=1'
        end
        build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
      end
    end
`;

    // Prefer running after react_native_post_install so nothing it does can
    // clobber the setting; fall back to the top of the post_install block.
    const afterRnPostInstall = /react_native_post_install\([\s\S]*?\n\s*\)\n/;

    if (afterRnPostInstall.test(podfile)) {
      config.modResults.contents = podfile.replace(
        afterRnPostInstall,
        (match) => `${match}${patch}`
      );
    } else if (podfile.includes("post_install do |installer|")) {
      config.modResults.contents = podfile.replace(
        "post_install do |installer|",
        `post_install do |installer|\n${patch}`
      );
    } else {
      throw new Error(
        "withMmkvMemsetFix: no post_install block found in the Podfile — " +
          "the MMKVCore memset_s fix was not applied."
      );
    }

    return config;
  });
};
